/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as OauthCallbackRouteImport } from './routes/oauth-callback'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPmRouteImport } from './routes/_authenticated/pm'
import { Route as AuthenticatedExpertRouteImport } from './routes/_authenticated/expert'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPmRoute = AuthenticatedPmRouteImport.update({
  id: '/pm',
  path: '/pm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpertRoute = AuthenticatedExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/pitch': typeof PitchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/expert': typeof AuthenticatedExpertRoute
  '/pm': typeof AuthenticatedPmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/pitch': typeof PitchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/expert': typeof AuthenticatedExpertRoute
  '/pm': typeof AuthenticatedPmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/pitch': typeof PitchRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/expert': typeof AuthenticatedExpertRoute
  '/_authenticated/pm': typeof AuthenticatedPmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/oauth-callback'
    | '/pitch'
    | '/admin'
    | '/expert'
    | '/pm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/oauth-callback'
    | '/pitch'
    | '/admin'
    | '/expert'
    | '/pm'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/oauth-callback'
    | '/pitch'
    | '/_authenticated/admin'
    | '/_authenticated/expert'
    | '/_authenticated/pm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  PitchRoute: typeof PitchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pm': {
      id: '/_authenticated/pm'
      path: '/pm'
      fullPath: '/pm'
      preLoaderRoute: typeof AuthenticatedPmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expert': {
      id: '/_authenticated/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof AuthenticatedExpertRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedExpertRoute: typeof AuthenticatedExpertRoute
  AuthenticatedPmRoute: typeof AuthenticatedPmRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedExpertRoute: AuthenticatedExpertRoute,
  AuthenticatedPmRoute: AuthenticatedPmRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  PitchRoute: PitchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
